[package]
name = "consumers"
version = "0.1.0"
edition = "2021"

[dependencies]
services = { path = "../../services" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true}