[package]
name = "services"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lapin ={ workspace = true }
tokio ={ workspace = true }
futures-lite ={ workspace = true }